ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: development

server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true

---
spring:
  profiles: production

server:
  port: 9001

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/
  instance:
    preferIpAddress: true

