ribbon:
  eureka:
    enabled: true

---
spring:
  profiles: development

server:
  port: 9001

logging:
  level:
    ROOT: info
    me.jefferlau: debug

---
spring:
  profiles: production

server:
  port: 9000

logging:
  level: warn

---
spring:
  profiles: test

server:
  port: 9000

logging:
  level: info
